### ISSUE TITLE
Re-implement macros through Liquid templates

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#28]
The code is really messy for handling macros, and the more functionality we want to add, it's going to end up like Twine with its bizarreness. I'm going to advocate that instead of continuing to write our own macro handling, we implement [Liquid.](https://help.shopify.com/themes/liquid)

This implementation would be done through [liquid-node](https://github.com/sirlantis/liquid-node) and [liquid.js](https://github.com/heupel/liquid.js). I've done some tests and think this would be viable and yield the following advantages:

* Control flow in Markdown that allows for `if`, `else`, `unless`, `for`, etc. inside of text files
* Recursive access to the global scope when including variables, i.e. {{ object.property }} 
    * We can also accomplish this in a more temporary way as explained in issue #29
* Human-readable macros
    * `call` for functions instead of `#`
    * `section` for sections instead of {{ }}
* [Apply filters and custom filters to variables](https://help.shopify.com/themes/liquid/filters)

I've created a branch in my fork to get working on this. @invicticide I want to know what you think before I go much further with it, but I think this would be huge for extensibility in Fractive and make larger projects like Space Bard more sane.

**Comment by invicticide** [comment]
I'm not super excited about Liquid for this. A major goal I have for Fractive is to keep the Markdown story text as clean as possible, with minimal additional markup; that's the main reason game logic and state are pushed out to Javascript. With Liquid, you're encouraged to do control flow and non-trivial variable/object operations right in the story text, which starts to look a lot like that embedded Twine scripting that made me want to do things differently in the first place.

It also creates some ambiguities for certain things. Imagine I'm tracking an inventory (a list of strings) and want to now list the contents of that inventory. The way I see that working in Fractive is something like:

```
[ ./text.md ]
You are carrying:
{#ListInventory}

[ ./script.js ]
function ListInventory() { return inventory.join('\n'); }
```

The Liquid implementation might look something like:

```
[ ./text.md ]
You are carrying:
{% for item in inventory %}
  {{ item.name }}
{% endfor %]
```

This is definitely subjective, but I feel like the former's Markdown is much more clear. And for the latter, I'm worried about making authors write additional Javascript boilerplate to expose their variables for use by Liquid (unless all Javascript declarations are somehow automatically in scope for Liquid; I haven't yet seen anything that suggests which way it works). One of the reasons I backed off from integrating webpack was that it too would've required authors to do boilerplate work to make their Javascript declarations available to their source text.

This example also raises the question for authors: which is the "right" way to implement story logic? I'd prefer to avoid presenting that kind of ambiguity. It becomes especially messy when people start mixing methods, i.e. sometimes control flow is handled in Liquid, and other times in Javascript. If we just have Markdown and Javascript, then logic *obviously* must live in Javascript; then it's easy for authors to make the "right" decision, because there's only one.

However, Liquid does provide some nice features which could inspire similar features in Fractive:

- **Textual tag names:** Using `section` instead of `@` for example. In Fractive, these could be alised, so `{@foo}` and `{section:foo}` resolve to the same thing.
- **Filters:** Text transformations could be especially useful for locale-based stuff (currency signs, decimal points) as well as for artistic effect (all caps, dialect mangling). Macro decorators could provide a syntax for this, e.g. `{$someValue:allCaps}`
- **Theme tags:** These provide a clean way to format and style sections of source text. Not sure on the best syntax for these yet.

I'm not comfortable bringing along all the *other* stuff (operators, control flow, all the Shopify cruft, etc.) just to get those features, but I do think they're valuable design references to work from.

All this being said, you're certainly welcome to dive into this in a fork; that's the point of open-source, after all. ;) And maybe I'll become more convinced after seeing a non-theoretical implementation and/or clear use cases.

**Comment by NQNStudios** [comment]
> And for the latter, I'm worried about making authors write additional Javascript boilerplate to expose their variables for use by Liquid (unless all Javascript declarations are somehow automatically in scope for Liquid; I haven't yet seen anything that suggests which way it works). One of the reasons I backed off from integrating webpack was that it too would've required authors to do boilerplate work to make their Javascript declarations available to their source text.


As far as this goes, you pass in a dictionary to the render () function and it automatically resolves . access, so essentially if we pass `window` to that, my thinking is it will access all global JavaScript variables much the same as how we have it now.

You're right that it adds a more complicated markup similar to Twine's. My reasoning is that Liquid would still be preferable because it's extensible and not proprietary. But it definitely represents a fundamental shift in the target developer to use Fractive. I can see why it might be better to leave things as-is, but if I get the chance I may do an implementation in my fork if only for my own experience.

**Comment by NQNStudios** [comment]
(Going to use this issue's comment thread to think out loud for a bit.)

I'm thinking a partially restricted Liquid parser might be ideal. Some of the core Liquid tags are potentially hazardous to the common Fractive dev:

* `assign` and `capture` can create variables that will only be accessible by Liquid and not by JavaScript. Ideally, we want Liquid markup to be "readonly", i.e. Liquid can access JavaScript variables but not create or change them.
* `increment` and `decrement` for the same reason
* `ifchanged` from liquid-node -- what does it even do?
* `for` encourages awkward markup and too much logic in the Markdown, like you pointed out

However, the following could be redefined or exploited to solve other existing problems and add functionality:

* `if` and `unless` allow for simple control switching that doesn't add too much clunky markup and might be more awkward when done through JavaScript.
* `case` for the same reason -- unless we consider the markup too clunky
* `include` can be redefined to expand a section inside another section
* `raw` would provide a more elegant solution to issue #8 than the current one

I think disabling and redefining built-in tags is possible, but I'm going to test it out.

**Comment by NQNStudios** [comment]
Looking at the [built-in filters](https://github.com/sirlantis/liquid-node/blob/master/src/liquid/standard_filters.coffee) implemented by liquid-node, I'm not as concerned that any of these will need to be disabled.

**Comment by NQNStudios** [comment]
One of the biggest potential oddities is tricking Liquid into processing the files in two separate passes, the way Fractive does right now (one time through the Compiler to generate HTML, then at runtime, use Core to expand the HTML further).

It seems to me we want something like this to happen:

Liquid's first pass (triggered at compile-time by Compiler):
* Expand section declarations into divs surrounding the entire section
* Expand link declarations into properly formed links

Liquid's second pass (triggered at runtime by Core):
* Expand variables
* Expand function calls
* Expand `include`s
* Expand `if`, `unless, `case`, etc.

I have a somewhat hackish solution. Compiler can initialize the Liquid engine with its own restricted set of tags, and process the Markdown files. At runtime, Core will initialize an engine that is fully enabled with the tags we want to be resolved at runtime. Hopefully Fractive devs won't need to even understand that two passes are going on under the hood.

The part I haven't solved is tricking Liquid not to expand variables at compile-time (which would throw compile-time errors, because the variables aren't even defined until the JavaScript runs).

**Comment by NQNStudios** [comment]
Ok I'm willing to admit this was a mistake. 👎

**Comment by NQNStudios** [comment]
The deciding factors for me were the amount of jankiness I was introducing just to *remove* functionality, and the lack of documentation on liquid-node making it a nightmare to implement anything. Also why does it have to be asynchronous?! :sob:
