### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#36]
# Feature

Eventually Fractive is going to need a back button like Twine has.

# Expected Behavior

I can imagine two different ways of implementing this:
* Like Twine does, the back button always takes you to the previous section **from the beginning**, so any text that was expanded from links is gone, and the links are reset.
* Maybe a preferable behavior: returning to the previous section as it was presented immediately before switching to the current section.

It might be worth implementing both and letting users choose between them by calling a Core function or even setting a flag in `fractive.json`. Because I can think of situations where Twine's behavior was annoying, but also situations where it would be preferable.

# Implementation proposal

For the first method, we would need to maintain a stack of section id's that have been visited. The back button will call `Core.GotoSection()` to return to the beginning of the section at the top of the stack.

For the second method, we could utilize the `__history` div to copy over the state of the previous section exactly as it was.

# Custom Appearance

Similar to my proposal for #9's external link icon being defined as raw HTML in `fractive.json`, I think the same method could be used to let the user make the back button look however they want. Its position would be definable in template.html in the same way the `__currentSection` and `__history` divs are.

**Comment by NQNStudios** [comment]
I'm gonna take a crack at implementing this. Another feature I think the back button should have is a callback so users can handle the back button with custom logic if they want to.

**Comment by invicticide** [comment]
For the callback, take a look at `Core.AddEventListener` and the `Core.OnGotoSection` event. I don't know if this is even a good way to handle this but it is *a* way to handle it and whatever we do we should make sure all callbacks are handled the same way from the end user's perspective, and preferably with nice/easy UX for subscribing to these things.

For the functionality more generally, I've been avoiding thinking too much about it because every time I think about I realize I'm staring into a great gaping maw of unanswered questions and tricky edge cases. Will be interesting to see how this comes together. ;)

**Comment by invicticide** [comment]
This was resolved by PR #42
