### ISSUE TITLE
Ability to web link directly to specific sections

### ISSUE THREAD

**Issue by NQNStudios** [invicticide/fractive#66]
What I'm imagining is index.html processing some optional URL parameters, like this:

`http://balladofthespacebard.com/index.html?start=Episode2`

This link would lead directly to the section named Episode2, instead of Start.

There are two scenarios where I can imagine this functionality being especially useful:

* Debugging as a Fractive dev, I'm constantly clicking through the start of a story just to get to the section I just made changes on. I could solve that by constantly adding cheat links to the Start section, but that's messy.
* If making episodic hypertext (which describes like, 3/4 of my current hypertext projects) it will be advantageous to be able to distribute links that skip part of the story. For Stream of Pretentiousness, which is all very short vignettes, it would be so ideal if I were writing a blog post, I could link to just the right section.

**Comment by invicticide** [comment]
Yeah I've been thinking about something similar for a while. There's this tangential potential use case for Fractive as a vaguely Jekyll-esque website builder but the current lack of deep-linking is a fatal flaw for that.

**Comment by NQNStudios** [comment]
Jekyll-esque is exactly right. I might eventually switch my whole website over from Jekyll to Fractive.

**Comment by invicticide** [comment]
Aside from the lack of deep-linking, the other (currently) shitty thing about using Fractive for a website as opposed to a hypertext story is that on a website you probably don't want all your resources compiled into a single html file, particularly if your site is going to be image-heavy.

I did [a quick experiment](https://github.com/invicticide/snap) a couple weeks ago with a pseudo-fork of Fractive that dumps out separate html files for a more website-like deployment. It's kinda promising. I haven't done much with it beyond an initial proof of concept, though, and I split it off because I don't want Fractive itself to get pulled too far off its original/core goal of making hypertext stories... but this is all stuff that's swirling around in my head, at any rate.

**Comment by NQNStudios** [comment]
When this is implemented, there should also be a project configuration option to have the URL in the browser window update to reflect the URL of the current section. So if an author wants to let players link to specific sections, they have an easy way of doing that, but if an author wants to hide section names or make it hard to skip content, that can be the default behavior.
